# Nombre de tu proyecto en Cloudflare Pages
name                     = "progresso-dev"

# Fecha de compatibilidad estable
compatibility_date       = "2024-01-01"

# Carpeta donde Astro deja el build tras `npm run build`
pages_build_output_dir   = "./dist"

# Configuración de variables de entorno
[vars]
# Estas variables se pueden configurar en Cloudflare Pages
API_URL = ""

# KV namespace para tu binding
[[kv_namespaces]]
binding = "PROGRESSO_KV"
# El ID se debe configurar en Cloudflare Pages
