# Nombre de tu proyecto en Cloudflare Pages
name                     = "progresso-dev"

# Fecha de compatibilidad (siempre explícita, no "Latest")
compatibility_date       = "2025-05-01"

# Carpeta donde Astro deja el build tras `npm run build`
pages_build_output_dir   = "./dist"

# KV namespace para tu binding “progresso_dev”
[[kv_namespaces]]
binding = "progresso_dev"
id      = "0914cacba76d430c9fb3ab05a514efb3"
